name: interview
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.15.1=hb03c661_0
  - anyio=4.12.0=pyhcf101f3_0
  - aom=3.9.1=hac33072_0
  - attr=2.5.2=h39aace5_0
  - av=13.1.0=py312h3fd8226_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhd8ed1ab_1
  - backports.zstd=1.2.0=py312h90b7ffd_0
  - beautifulsoup4=4.14.3=pyha770c72_0
  - brotli-python=1.2.0=py312hdb49522_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cachecontrol=0.14.3=pyha770c72_0
  - cachecontrol-with-filecache=0.14.3=pyhd8ed1ab_0
  - cairo=1.18.4=he90730b_1
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=2.0.0=py312h460c074_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cleo=2.1.0=pyhd8ed1ab_1
  - click=8.3.1=pyh8f84b5b_1
  - cloup=3.0.8=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - crashtest=0.4.1=pyhd8ed1ab_1
  - cryptography=46.0.3=py312ha4b625e_1
  - dav1d=1.2.1=hd590300_0
  - dbus=1.16.2=h24cb091_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - distlib=0.4.0=pyhd8ed1ab_0
  - dulwich=0.22.8=py312h12e396e_0
  - exceptiongroup=1.3.1=pyhd8ed1ab_0
  - ffmpeg=7.1.1=gpl_hbbdf940_911
  - filelock=3.20.1=pyhd8ed1ab_0
  - findpython=0.6.3=pyhff2d567_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - freetype=2.14.1=ha770c72_0
  - fribidi=1.0.16=hb03c661_0
  - gdk-pixbuf=2.44.4=h2b0a6b4_0
  - glcontext=3.0.0=py312h835c14e_2
  - glib=2.86.3=h5192d8d_0
  - glib-tools=2.86.3=hf516916_0
  - gmp=6.3.0=hac33072_2
  - graphite2=1.3.14=hecca717_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.2.0=h6083320_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=78.1=h33c6efd_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - intel-gmmlib=22.9.0=hb700be7_0
  - intel-media-driver=25.3.4=hecca717_0
  - isosurfaces=0.1.2=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=pyhd8ed1ab_2
  - jaraco.context=6.0.2=pyhcf101f3_1
  - jaraco.functools=4.4.0=pyhd8ed1ab_0
  - jeepney=0.9.0=pyhd8ed1ab_0
  - keyring=25.7.0=pyha804496_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - level-zero=1.26.3=hb700be7_0
  - libabseil=20250512.1=cxx17_hba17884_0
  - libass=0.17.4=h96ad9f0_0
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libcap=2.77=h3ff7636_0
  - libcblas=3.11.0=5_h0358290_openblas
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libegl=1.7.0=ha4b6fd6_2
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libflac=1.5.0=he200343_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgd=2.3.3=h5fbf134_12
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.86.3=h6548e54_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=15.2.0=he0feb66_16
  - libhwloc=2.12.1=default_hafda6a7_1003
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hb9d3cd8_1
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libopenvino=2025.2.0=hb617929_1
  - libopenvino-auto-batch-plugin=2025.2.0=hed573e4_1
  - libopenvino-auto-plugin=2025.2.0=hed573e4_1
  - libopenvino-hetero-plugin=2025.2.0=hd41364c_1
  - libopenvino-intel-cpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-gpu-plugin=2025.2.0=hb617929_1
  - libopenvino-intel-npu-plugin=2025.2.0=hb617929_1
  - libopenvino-ir-frontend=2025.2.0=hd41364c_1
  - libopenvino-onnx-frontend=2025.2.0=h1862bb8_1
  - libopenvino-paddle-frontend=2025.2.0=h1862bb8_1
  - libopenvino-pytorch-frontend=2025.2.0=hecca717_1
  - libopenvino-tensorflow-frontend=2025.2.0=h0767aad_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hecca717_1
  - libopus=1.6=h0fd0de7_0
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.53=h421ea60_0
  - libprotobuf=6.31.1=h49aed37_4
  - librsvg=2.60.0=h61e6d4b_0
  - libsndfile=1.2.2=hc7d488a_2
  - libsqlite=3.51.1=hf4e2dac_1
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libsystemd0=258.3=h6569c3e_0
  - libtiff=4.7.1=h9d88235_1
  - libudev1=258.3=h6569c3e_0
  - libunwind=1.8.3=h65a8314_0
  - liburing=2.12=hb700be7_0
  - libusb=1.0.29=h73b1eb8_0
  - libuuid=2.41.3=h5347b49_0
  - libva=2.23.0=he1eb515_0
  - libvorbis=1.3.7=h54a6638_2
  - libvpl=2.15.0=h54a6638_1
  - libvpx=1.14.1=hac33072_0
  - libvulkan-loader=1.4.328.1=h5279c79_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=he237659_1
  - libxml2-16=2.15.1=hca6bf5a_1
  - libzlib=1.3.1=hb9d3cd8_2
  - manimpango=0.6.0=py312h6802ac9_0
  - mapbox_earcut=1.0.3=py312hf890105_2
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - moderngl=5.11.1=py312h4f16dfd_1
  - moderngl-window=3.1.1=pyh29332c3_1
  - more-itertools=10.8.0=pyhcf101f3_1
  - mpg123=1.32.9=hc50e24c_0
  - msgpack-python=1.1.2=py312hd9148b4_1
  - ncurses=6.5=h2d0b736_3
  - networkx=3.6.1=pyhcf101f3_0
  - numpy=2.4.0=py312h33ff503_0
  - ocl-icd=2.3.3=hb9d3cd8_0
  - opencl-headers=2025.06.13=h5888daf_0
  - openh264=2.6.0=hc22cd8d_0
  - openjpeg=2.5.4=h55fea9a_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py312hf79963d_1
  - pango=1.56.4=hadf4263_0
  - pbs-installer=2025.12.17=pyhd8ed1ab_0
  - pcre2=10.47=haa7fec5_0
  - pillow=12.0.0=py312h50c33e8_2
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pkginfo=1.12.1.2=pyhd8ed1ab_0
  - platformdirs=4.5.1=pyhcf101f3_0
  - poetry=2.1.2=pyha804496_0
  - poetry-core=2.1.2=pyhd8ed1ab_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pugixml=1.15=h3f63f65_0
  - pulseaudio-client=17.0=h9a6aba3_3
  - pycairo=1.29.0=py312h2596900_0
  - pycparser=2.22=pyh29332c3_1
  - pydub=0.25.1=pyhd8ed1ab_1
  - pyglet=2.1.11=pyhd8ed1ab_0
  - pyglm=2.8.3=py312hd9148b4_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyproject_hooks=1.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.12=hd63d673_1_cpython
  - python-build=1.3.0=pyhff2d567_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-installer=0.7.0=pyhff2d567_1
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.12=8_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.3=py312h8a5da7c_0
  - rapidfuzz=3.14.3=py312h1289d80_1
  - readline=8.3=h853b02a_0
  - requests=2.32.5=pyhcf101f3_1
  - requests-toolbelt=1.0.0=pyhd8ed1ab_1
  - rich=14.2.0=pyhcf101f3_0
  - scipy=1.16.3=py312h54fa4ab_2
  - screeninfo=0.8.1=py312h7900ff3_3
  - sdl2=2.32.56=h54a6638_0
  - sdl3=3.2.28=h3b84278_0
  - secretstorage=3.4.1=py312h7900ff3_0
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_2
  - six=1.17.0=pyhe01879c_1
  - skia-pathops=0.9.1=py312hd9148b4_0
  - snappy=1.2.2=h03e3b7b_1
  - sniffio=1.3.1=pyhd8ed1ab_2
  - soupsieve=2.8.1=pyhd8ed1ab_0
  - srt=3.5.3=pyhd8ed1ab_1
  - svgelements=1.9.6=pyhd8ed1ab_0
  - svt-av1=3.1.2=hecca717_0
  - tbb=2022.3.0=h8d10470_1
  - tk=8.6.13=noxft_ha0e22de_103
  - tomli=2.3.0=pyhcf101f3_0
  - tomlkit=0.13.3=pyha770c72_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - trove-classifiers=2025.12.1.14=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=h8577fbf_0
  - urllib3=2.6.2=pyhd8ed1ab_0
  - virtualenv=20.35.4=pyhd8ed1ab_0
  - watchdog=6.0.0=py312h7900ff3_2
  - wayland=1.24.0=hd6090a7_1
  - wayland-protocols=1.47=hd8ed1ab_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xkeyboard-config=2.46=hb03c661_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.2=hb03c661_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - yaml=0.2.5=h280c20c_3
  - zipp=3.23.0=pyhcf101f3_1
  - zlib-ng=2.3.2=hceb46e0_1
  - zstandard=0.25.0=py312h5253ce2_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - manim==0.19.1
prefix: /home/tom/miniconda3/envs/interview
